---
title: "Introduction to Spatial Data Analysis in R"
subtitle: "Exercises"
author: "Adithi Upadhya, Meenakshi Kushwaha"
institute: "ILK Labs"
date: "20th June 2022 (updated: `r Sys.Date()`)"
output:
  html_document:
    code_folding: hide
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load Libraries  


```{r, message = FALSE, warning = FALSE}
library(sf) # for vector data
library(raster) # for raster data
library(here) # for specifying working directory
library(tidyverse)
library(leaflet) # for interactive maps
library(ggplot2) # plotting 
library(ggspatial)

```

### Your data set

## Reading vector data 
## Reading shp file

```{r Read and plot shapefile}
data <- read.csv("data/spotted.csv", sep = ",")
prj4string <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"
my_projection <- st_crs(prj4string)
data_sf <- st_as_sf(data, coords = c("Longitude", "Latitude"), crs = my_projection)

my_vector <- st_read(here("data", "BBMP_Boundary.shp"))
plot(my_vector)
## add spotted data to this
## make leaflet map
```


```{r Vector operations, eval = FALSE, echo = TRUE}
st_area()
st_centroid()
st_boundary()

# buffer later
```

```{r Reading and re raster file}
my_raster <- raster(here("data", "Ban_Temp_Mar2022.tif"))
res(my_raster)

ncell(my_raster)

small_raster <- aggregate(my_raster, 2)
ncell(small_raster)

```


- Can you change the style of the north arrow
  - Check here https://rdrr.io/cran/ggspatial/man/north_arrow_orienteering.html
```{r Making your own map}
bangalore_boundary <- st_read("data/BBMP_Boundary.shp")
bangalore_boundary <- st_transform(bangalore_boundary, crs = my_projection)

ggplot() + geom_sf(data = bangalore_boundary, color = "green", size = 2, alpha = 0.1, fill = "green") +
  geom_sf(data = data_sf, color = "blue", size = 2) + 
  theme_bw() +
  annotation_scale(location = "bl", width_hint = 0.5) +
  annotation_north_arrow(location = "bl", which_north = "true", 
                         pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
                         style = north_arrow_fancy_orienteering) +
  coord_sf(xlim = c(77.4, 77.8), ylim = c(12.8, 13.2))
```

- Fill in the blanks to make your map interactive, 
- The defaulty map do not use "addTiles()"
   - comment out the code on line 78 to check
- Can you change the points from circles to a different shape
[We have not covered it in the tutorial but you can check 
available shapes here - https://rstudio.github.io/leaflet/markers.html]

```{r Making your map interactive, eval = FALSE, echo = TRUE}

_______(bangalore_boundary) %>% 
  addTiles() %>% 
  addPolygons(color = "green") %>%
      addCircles(
        data = data,
        lng = ~ Longitude,
        lat = ~ Latitude,
        radius = 20,
        weight = 20,
        fill = TRUE)
```

